enableGlobalCache: true

nodeLinker: node-modules

npmScopes:
  alorel:
    npmRegistryServer: "https://npm.pkg.github.com/alorel"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-rc.js
